### ISSUE TITLE
estimated release date?

### ISSUE THREAD

**Issue by Danfun64** [kuleshov/audio-super-res#1]
If this technique is real, than it's amazing. I'm curious how long it's going to take before you feel comfortable releasing the tech publicly so that people can input their LQ audio files and get something better out of them...

**Comment by kuleshov** [comment]
Sure :) How about after the NIPS deadline on May 19? The method is not that
difficult to reimplement if you're interested to play with it sooner.

**Comment by achalshah20** [comment]
Hi, I would like to test some of my LQ audio files and see the results of this technique. Is the implementation ready to be published publicly? Thanks!

**Comment by kuleshov** [comment]
Our code is now available!
