### ISSUE TITLE
Error regarding 

### ISSUE THREAD

**Issue by alicebeauti** [kuleshov/audio-super-res#10]
Hi Volodymyr ,

Thanks for sharing your nice work. I have successfully ran through the preparation of data, however, I  met a bug when trying the run training job by the following command.

python run.py train --train ../data/vctk/speaker1/vctk-speaker1-train.4.16000.8192.4096.h5 --val ../data/vctk/speaker1/vctk-speaker1-val.4.16000.8192.4096.h5 -e 120 --batch-size 2 --lr 3e-4 --logname singlespeaker

The bug that I got is shown as following:

audiounet.py", line 111, in orthogonal_init
    return orthogonal(shape, name=name, dim_ordering=dim_ordering)
TypeError: __init__() got an unexpected keyword argument 'dim_ordering'

I have done a massive search and tried to upgrade the version of Keras to latest one 2.2.0. Albeit, the error still shows up. Thus, could you please let me know if you have any solution to solve this problem? Thank you for your help!

Best regards,
Alice

**Comment by JSai23** [comment]
If I may ask, what version of python are you running this in and are you using a virtual environment

**Comment by kuleshov** [comment]
Python 2.7 and you may find a list of packages we used and their versions
in the readme.

**Comment by Sawyerb** [comment]
We've updated the code to run with Python 3.7 and with more recent versions of a lot of the core packages.
