### ISSUE TITLE
Error regarding 'dim_ordering'

### ISSUE THREAD

**Issue by alicebeauti** [kuleshov/audio-super-res#11]
Hi Volodymyr ,

Thanks for sharing your nice work. I have successfully ran through the preparation of data, however, I  met a bug when trying the run training job by the following command.

python run.py train --train ../data/vctk/speaker1/vctk-speaker1-train.4.16000.8192.4096.h5 --val ../data/vctk/speaker1/vctk-speaker1-val.4.16000.8192.4096.h5 -e 120 --batch-size 2 --lr 3e-4 --logname singlespeaker

The bug that I got is shown as following:

audiounet.py", line 111, in orthogonal_init
    return orthogonal(shape, name=name, dim_ordering=dim_ordering)
TypeError: __init__() got an unexpected keyword argument 'dim_ordering'

I have done a massive search and tried to upgrade the version of Keras to latest one 2.2.0. Albeit, the error still shows up. Thus, could you please let me know if you have any solution to solve this problem? Thank you for your help!

Best regards,
Alice

**Comment by kuleshov** [comment]
Hi Alice, sorry about this. I think most likely the problem is that the
code was for Keras 1, and that argument was removed in Keras 2. I haven't
checked, but I suspect you may get away with not giving the dim_ordering
argument.

**Comment by alicebeauti** [comment]
Hi Volodymyr, Thank you for your rapid response. I have followed your suggestion by downgrading the version of Keras to 1. This time, I could successfully submit the training job without showing the error relevant to 'dim_ordering'. However, there is another error popping up as following:

D-Block:  (?, ?, 128)
D-Block:  (?, ?, 256)
D-Block:  (?, ?, 512)
D-Block:  (?, ?, 512)
U-Block:  (?, ?, 1024)
U-Block:  (?, ?, 1024)
U-Block:  (?, ?, 512)
U-Block:  (?, ?, 256)
(?, ?, 1)
creating train_op with params: {'layers': 4, 'alg': 'adam', 'batch_size': 1, 'lr': 0.0003, 'b1': 0.9, 'b2': 0.999}
Segmentation fault (core dumped)

I checked online for this message and found out it may relate to the GPU memory issue. But I have a relatively large RAM with 24Gb for my box. In addition, I also reduced the amount of training wav in one speaker, and the message is still there. 

Sorry to bother you again. Please let me know if you have any suggestions. Thank you.

Best regards,
Alice

**Comment by kuleshov** [comment]
Unfortunately, this seems like a bug in some lower-level library that is
being called from Tensorflow. I don't think you're running out of GPU
memory. Maybe just firing up an ec2 instance or a docker container where
the low-level libraries are recompiled would be one way to approach this.

**Comment by cherylchan921** [comment]
Hi Alice, I met the same problem with you. Did you solve it?


> Hi Volodymyr, Thank you for your rapid response. I have followed your suggestion by downgrading the version of Keras to 1. This time, I could successfully submit the training job without showing the error relevant to 'dim_ordering'. However, there is another error popping up as following:
> 
> D-Block: (?, ?, 128)
> D-Block: (?, ?, 256)
> D-Block: (?, ?, 512)
> D-Block: (?, ?, 512)
> U-Block: (?, ?, 1024)
> U-Block: (?, ?, 1024)
> U-Block: (?, ?, 512)
> U-Block: (?, ?, 256)
> (?, ?, 1)
> creating train_op with params: {'layers': 4, 'alg': 'adam', 'batch_size': 1, 'lr': 0.0003, 'b1': 0.9, 'b2': 0.999}
> Segmentation fault (core dumped)
> 
> I checked online for this message and found out it may relate to the GPU memory issue. But I have a relatively large RAM with 24Gb for my box. In addition, I also reduced the amount of training wav in one speaker, and the message is still there.
> 
> Sorry to bother you again. Please let me know if you have any suggestions. Thank you.
> 
> Best regards,
> Alice

**Comment by Sawyerb** [comment]
This error should no longer be an issue now that the code runs with TF 2.4 and Keras 2.4,
