### ISSUE TITLE
What is the purpose of the patches?

### ISSUE THREAD

**Issue by JSai23** [kuleshov/audio-super-res#14]
What are the purpose of the patches and how would i modify the prep_vctk file to work with my own data set?

**Comment by JahnKhan** [comment]
here is an example, the Shape of the data after preprocessing looks like this:
Shape of X: (3328, 8192, 1)
Shape of Y: (3328, 8192, 1)

that means that there is one patch that has 8192 time-steps and 1 feature. It's like a table of 8192 rows and 1 column. Where the rows are the time and the column is the value of your audiosignal.
An example applied to an image: if you have a 4 X 4 Image and you cut it into smaller parts for example  2 X 2 pieces. Than you will have 4 times  2 X 2 pieces. How much of your pieces you want to create depends on your data.
The next thing is the batchsize. The batchsize is in this project is a multiple of the patchsize. The batchsize defines, how many patches you want to feed in every epoch into your convolutional neuronal network. A convolutional neuronal network does not load the whole data at once it, processes the data in batches. The size of batch depends on your machine resources, and has an effect on your training speed and result.

please correct me if I did not get it right.
@kuleshov

**Comment by Sawyerb** [comment]
@JahnKhan, yep, you're correct. 

@JSai23, if you have `.wav` files, I think you should be able to process them with `prep_vtck.py` with minimal modifications. You'd mainly need to change how `add_data` finds the files to load.
