### ISSUE TITLE
question of results in samples folder

### ISSUE THREAD

**Issue by wl3b10s** [kuleshov/audio-super-res#16]
1. the name of the file  *.pr.wav and *.sp.wav . which is the result of the paper's super resolution network? and what is the other?

2. Sp1.3.4.sp.wav seems has some blind area in the spectrum view on some freqency. why? nearly all *.sp.wav data has this phenomenon.

thanks.

**Comment by Sawyerb** [comment]
1. `sp.wav` in the README is a typo. The model's predictions are saved with the `*.pr.wav` suffix. 
2. I'm not sure what file you're referring to. How did you generate Sp1.3.4.sp.wav?
