### ISSUE TITLE
Convolution layer in upsampling block

### ISSUE THREAD

**Issue by achalshah20** [kuleshov/audio-super-res#2]
Hi, 

I read this paper and it is pretty good. I am trying to implement this paper. I came across few following questions which I am not able to answer from the paper. 

1. Why convolution layer in upsampling block? Only subpixel upsampling layer is not enough?
2. What are the parameters of convolution layer in both upsampling and downsampling block? Like number of initial filters in downsampling block, number of filters in upsampling block convs.
3. What is a filter size you used in convolution layer?
4. What is B- bottleneck block? Just a pass through from downsampling to upsampling block? 

![up sampling downsampling block](https://user-images.githubusercontent.com/9772589/27193295-3361b554-51b3-11e7-93da-4457f0855368.png)

Thanks. Moreover, please let me know if you are planning to release this code for public. It would be really helpful. 

- Achal

**Comment by kuleshov** [comment]
Hi Achal, you can now have a look at our code.

The upsampling convolutions are necessary to produce the waveforms from the intermediary feature representations in the model.
