### ISSUE TITLE
Upload  a pre trained model?

### ISSUE THREAD

**Issue by arnavvats** [kuleshov/audio-super-res#20]
Can a pre trained model be uploaded to the repo? Some of us dont have enough computation power to data such a massive model.

**Comment by alokprasad** [comment]
@kuleshov  where i can find trained model?

**Comment by JahnKhan** [comment]
yeah push a trained model please

**Comment by bc** [comment]
I'd really appreciate this too, thanks!

**Comment by LXP-Never** [comment]
In order to make it easy for us to reproduce the effect, who can give a trained model?

**Comment by Sawyerb** [comment]
@arnavvats @alokprasad @JahnKhan @bc @LXP-Never if any you are still interested in a pre-trained model, let me know and I'll send you one. The models are in the 100s of MB, so I'd like to avoid pushing one.

**Comment by LXP-Never** [comment]
> @arnavvats @alokprasad @JahnKhan @bc @ LXP-如果您仍然对预训练模型感兴趣，请告诉我，我会给您发送。这些模型的大小为100 MB，因此我想避免推一个。

Although I ran through the project last year, I still want to see the results you ran. Can you share the trained model with me? I will thank you very much, my email: lxpnever@gmail.com

**Comment by alokprasad** [comment]
@Sawyerb 
Actually i guess there is limit of 100mb in github.The way i upload is using split.

**Splitting**
split -b 99M inference_model.pb small_model  ->( create small_model.aa  small_model.ab small_model.ac)

**Merging**
cat small_model.* > inference_model.pb

**Comment by Sawyerb** [comment]
@LXP-Never @alokprasad I've uploaded a trained model to Google Drive. The link is in the README.

**Comment by LXP-Never** [comment]
> @LXP-Never @alokprasad I've uploaded a trained model to Google Drive. The link is in the README.

It will be very useful to me, thank you
