### ISSUE TITLE
How to flip phase if designing ASR in frequency domain instead of time domain?

### ISSUE THREAD

**Issue by TianYe2017** [kuleshov/audio-super-res#21]
Hi Professor

I am thinking of re_implementing an ASR model with very similar structure  but in frequency domain. Basically i will first apply STFT to the signal and split the specgram to log power map + phase map. During ASR, i only predict log power map, and expand phase map from lr to hr. However, i am not very clear how to expand the phase map. 

In one of the papers i read, the author says fliping and setting negative sign. For example, if ASR ratio is 4, you just flip three times. Say [1,2,3,4,5] is phase map of a signal, in x2 mode, hr phase map should be [1,2,3,4,5,-4,-3-2,-1]; and in x3 mode, the map should be [1,2,3,4,5,-4,-3,-2,-1,1,2,3,4]; and in x4 mode, it become [1,2,3,4,5,-4,-3,-2,-1,1,2,3,4,-4,-3,-2,-1].

To verify, i load a 16KHz audio, apply STFT, split power and phase, slice to 1/4  and flip three times to reconstruct the phase map. Finally through ISTFT i get output audio, but it sounds not right, the output have slightly phase shift.

My question is what is the correct way to expand the phase map when perform ASR?

Would be very appreciate if you can answer my question

Thanks a lot

Mike

**Comment by Sawyerb** [comment]
@TianYe2017, I'm not sure I understand your question. It seems like it might be better directed at the authors of the paper you read. Sorry that I can't be more helpful.
