### ISSUE TITLE
About the metrics SNR

### ISSUE THREAD

**Issue by YangYang** [kuleshov/audio-super-res#23]
As I know, in the paper, the metrics of SNR in the paper defined as the follow picture:
![image](https://user-images.githubusercontent.com/17808880/62750135-8f607b80-ba91-11e9-8c55-7fa125deb8cc.png)

But in your code, snr defined as:
"snr = 20 * tf.log(sqrn_l2_norm / sqrt_l2_loss + 1e-8) / tf.log(10.)"

About this, I have two questions.
1. In the paper, there is 10 * log(), but in your formular is 20 * log*()
2. In the paper, there is nothing about " / tf.log(10.)", but you have it.

I hope that I can get your help, I will be grateful.

**Comment by sailor88128** [comment]
The code is the same as the equation. It's "20" in code because of 'sqrt' and "/tf.log(10.)" for default base for tf.log() is e.

**Comment by YangYang** [comment]
Oh, it’s true!
But why don't you use this formula directly, but make such a transformation?
