### ISSUE TITLE
Update to keras 2.0 and Tensorflow 1.2

### ISSUE THREAD

**Issue by achalshah20** [kuleshov/audio-super-res#3]
I am using latest keras and tensorflow. I am getting many errors and many deprecation warnings. I can send PR with latest API changes for keras and tensorflow if you are interested!!!

**Comment by kuleshov** [comment]
If you could do that, I think it would be great!

**Comment by neerlent** [comment]
I would be interested in these changes as well.  If you're not ready to merge the changes yet, I'd be happy to test them out locally first.

**Comment by kuleshov** [comment]
I did these changes locally, and should be able to push them soon after a few internal verifications.

**Comment by kingkrausel** [comment]
Any news?

**Comment by polariss710** [comment]
Any news? I am wondering these changes also!

**Comment by nobillygreen** [comment]
Also very interested in this (as well as python 3 support). Any progress?

**Comment by polariss710** [comment]
No, I tried these codes in keras 2 and tensorflow 1.6, and I got a lot of errors which may be caused by the different version. Right now I am still working on it.
I sent mail to the author but hasn't received a reply yet.

**Comment by achalshah20** [comment]
I once tried to attempt this when tensorflow was around 1.2. But I couldn't able to reproduce the results so I am also waiting for official release from authors.

**Comment by polariss710** [comment]
Me too. But it seems that the authors is too busy to push new program to github, so we have to wait.

**Comment by nobillygreen** [comment]
I'm working a version using Tensorflow 1.5, python 3, and zero Keras utilization. I'll publish and share it **when** I get it working.

**Comment by polariss710** [comment]
I ‘ll appreciate	it if you do that.

**Comment by nobillygreen** [comment]
Hey polariss, I'm very close to having this working. Will likely publish something within the next few days, definitely within the next week. It doesn't have all the bells and whistles as this repo, but its at least functional.

**Comment by polariss710** [comment]
That’s great! I’m looking forward to seeing your work. Please let me know when you publish it. Thanks

**Comment by CivilEng-Fan** [comment]
Hi  kuleshov and Nobillygreen,
I am a PhD student from the department of civil engineering and willing to apply deep learning to our side. Totally a newbie of Python and machine learning, I have learned some basics of python 3 and Keras. It is so exciting to find your paper Kuleshov, because it is strongly correlated to my research. Trying to understood and shift your code to Python 3 friendly but without any python 2 basis, I can only run the 'run.py' to the last line with an error:  AttributeError: 'Namespace' object has no attribute 'func'.
I am here seeking for some help, and also, is there any new progress with the new version?
Many thanks to all of your work and kindly help. @kuleshov @nobillygreen

**Comment by bafonso** [comment]
@nobillygreen did you ever make some progress you could share? Just wondering before I tackle the code myself..

**Comment by o-zhu** [comment]
@nobillygreen Also chiming in to ask if you had any luck with the new version, thanks!

**Comment by Parsak87** [comment]
> Hey polariss, I'm very close to having this working. Will likely publish something within the next few days, definitely within the next week. It doesn't have all the bells and whistles as this repo, but its at least functional.

anyone made a updated version if this? @kuleshov  did you made it?
@nobillygreen  ? did you manage it? 
@bafonso you tackled it yourself ? 
:D  would be nice if someone can provice an updated version of this

**Comment by nobillygreen** [comment]
i never did manage to get this working. Unfortunately I moved onto a different project. At this point, I'd recommend doing it in TF 2.X. Not sure I'll ever get around to it.

**Comment by LXP-Never** [comment]
Me too, I have never run this project, can anyone provide code that can reproduce the paper?

**Comment by Sawyerb** [comment]
Apologies for the very delayed response. I have updated the repo to run with TF 2.4. (Albeit with substantial use of `tf.compat.v1`  . . . fully refactoring the code is a larger project than I have time for at the moment.) I've verified that the example commands in the README run. Let me know if you run into any problems.
