### ISSUE TITLE
ValueError: Shapes (4, 128, 128) and () are incompatible

### ISSUE THREAD

**Issue by tobischw** [kuleshov/audio-super-res#32]
Hi,

I know that the authors of this project have moved on, but I am still curious if anyone has ran into a similar issue regarding the shapes for the LSTM network.

I am only attempting to train the single-speaker.

First, I had to fork the project and fix the Makefile so that it pulls the VCTK-Corpus dataset from a different source (http://www.udialogue.org/download/VCTK-Corpus.tar.gz).

Second, I had to downgrade joblib to 0.11 due to a bug in the most recent Python2.7-compatible version.

This allowed me to download, make, and perform the downsampling on the dataset using the following parameters (the default parameters in the Makefile would simply not work for me and produce empty .h5 files):

```
sca = 4
sr = 16000

tr_dim = 8192
tr_str = 4096

va_dim = 8192
va_str = 4096
```

Now, whenever I am trying to train using the following (ignore the $output_name variables):

```
!python run.py train 
  --train ../data/vctk/speaker1/$train_output_name
  --val ../data/vctk/speaker1/$val_output_name -e 120 
  --batch-size 64 
  --lr 3e-4 
  --logname singlespeaker 
  --model audiotfilm 
  --r 4 
  --layers 4 
  --piano false
  --pool_size 8 
  --strides 8 
  --full true
```

I receive this error:
```
/content/gdrive/My Drive/audio-super-res/src
Using TensorFlow backend.
List of arrays in input file: [u'data', u'label']
Shape of X: (3328, 8192, 1)
Shape of Y: (3328, 8192, 1)
List of arrays in input file: [u'data', u'label']
Shape of X: (384, 8192, 1)
Shape of Y: (384, 8192, 1)
audiotfilm
building model...
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "run.py", line 172, in <module>
    main()
  File "run.py", line 169, in main
    args.func(args)
  File "run.py", line 119, in train
    model = get_model(args, n_dim, r, from_ckpt=False, train=True)
  File "run.py", line 155, in get_model
    strides=args.strides, opt_params=opt_params, log_prefix=args.logname)  
  File "/content/gdrive/My Drive/audio-super-res/src/models/audiotfilm.py", line 29, in __init__
    opt_params=opt_params, log_prefix=log_prefix)
  File "/content/gdrive/My Drive/audio-super-res/src/models/model.py", line 48, in __init__
    self.predictions = self.create_model(n_dim, r)
  File "/content/gdrive/My Drive/audio-super-res/src/models/audiotfilm.py", line 95, in create_model
    x_norm = _make_normalizer(x, nf, nb)
  File "/content/gdrive/My Drive/audio-super-res/src/models/audiotfilm.py", line 60, in _make_normalizer
    x_rnn = LSTM(output_dim = n_filters, return_sequences = True)(x_in_down)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 784, in build
    self.W = K.concatenate([self.W_i, self.W_f, self.W_c, self.W_o])
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1427, in concatenate
    return tf.concat(axis, [to_dense(x) for x in tensors])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1254, in concat
    tensor_shape.scalar())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 1023, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (4, 128, 128) and () are incompatible
```

Anyone see something like this before? Thanks!

**Comment by tobischw** [comment]
Bump. Anybody have any idea?

**Comment by vinayak19th** [comment]
I have the same error, any solution ?

**Comment by tobischw** [comment]
No idea. Very frustrating. I ended up using this version (https://github.com/leekh7411/Audio-Super-Resolution-Python3-TF), which actually ended up working for me.

**Comment by vinayak19th** [comment]
> No idea. Very frustrating. I ended up using this version (https://github.com/leekh7411/Audio-Super-Resolution-Python3-TF), which actually ended up working for me.

Thanks, I'll give it a look

**Comment by hqy2000** [comment]
Updating keras to `keras=1.2.2` seems to make it work.

**Comment by Lootwig** [comment]
Unrelated to your question, but do any of you guys get why there is an LSTM cell in the AudioTfilm model where there should actually be some sort of normalization going on? The comments are totally useless and apart from the down/bottle/up structure it barely resembles the model described in the paper anymore

**Comment by kuleshov** [comment]
Hey, I'm sorry that me and my co-authors are not able to provide support. Unfortunately, I only have the bandwidth to revisit this repo a few times a year. If you have specific request, you may try to reach out to my co-author Sawyer.

@Lootwig Regarding your question: AudioTFilm is a new layer that implements a new idea called TFilm or Temporal BatchNorm. We found it to really improve performance. You can read our NeurIPS paper on it here: https://papers.nips.cc/paper/2019/file/2afc4dfb14e55c6face649a1d0c1025b-Paper.pdf

**Comment by Sawyerb** [comment]
I've updated the code to Python 3.7 and updated Keras and Tensorflow to 2.4.0 and 2.4.1, respectively. I'm not seeing any errors on my machine, but if you run into any, let me know. I'm likewise sorry for the low level of support. Going forward, I'll be monitoring this repo more closely.

**Comment by hqy2000** [comment]
> I've updated the code to Python 3.7 and updated Keras and Tensorflow to 2.4.0 and 2.4.1, respectively. I'm not seeing any errors on my machine, but if you run into any, let me know. I'm likewise sorry for the low level of support. Going forward, I'll be monitoring this repo more closely.

Thank you for the hard work. Meanwhile, can you please upload the example model to somewhere else like Google Drive? It seems that it has reached the Git LFS quota limit and I cannot download it.

**Comment by Sawyerb** [comment]
I'm working on that. Might not get it done tonight, though.

**Comment by Sawyerb** [comment]
@hqy2000 thanks for the suggestion. I've uploaded a sample model to Google Drive. The link is in the README.

**Comment by tobischw** [comment]
Thanks for your response, guys. Absolutely no worries about no longer maintaining this - I think it's understood that you are working on new research now. Thank you so much for all of your hard work and a really interesting paper!

**Comment by Lootwig** [comment]
Gave it another try, but anaconda tells me the librosa==0.4.3 requirement is not compatible with python > 3.5.0, has anyone already tried another version of it that runs the source code?

**Comment by Sawyerb** [comment]
@Lootwig, can you post the error message that you're seeing? I'm able to import Librosa 0.4.3 when running python 3.7.10.

**Comment by Lootwig** [comment]
@Sawyerb here you go

```
$ conda install librosa==0.4.3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - librosa==0.4.3 -> python[version='2.7.*|3.4.*|3.5.*']

Your python: defaults/win-64::python==3.7.10=h6244533_0

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

```

**Comment by Sawyerb** [comment]
I'm not using Anaconda. Do you have pip? `pip install librosa==0.4.3` should work.

**Comment by Lootwig** [comment]
Yes I can use pip :) it's just that per [https://pypi.org/project/librosa/0.4.3/](), 3.7 is not officially supported.

But I'm all for a pragmatic solution - I think something that would already help *a ton* (for any paper also publishing its code, btw!) would be a documentation of the full environment by including a venv spec in the project root:
```
pip freeze > requirements.txt
```
Seeing as you've already been kind enough to come back to this repo's issue list - would you mind adding this to the repo?

**Comment by Sawyerb** [comment]
Thanks for the suggestion! I've added a `requirements.txt`. I've also upgraded to librosa 0.8.0.

**Comment by Lootwig** [comment]
Awesome, feel free to close the issue
