### ISSUE TITLE
LSTM kernel  not compatible with cuDNN and GPU utilization is low

### ISSUE THREAD

**Issue by jprobichaud** [kuleshov/audio-super-res#35]
I'm currently trying to train the multi-speaker/audiotfilm setup.  

I'm with CUDA 11 on a box with 4 pascal GPUs.  
When I launch the training process, I see messages like this for all the layers:
```
WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
```
Is that expected/normal?  The model is training though.

Also, I notice that the only GPU really used (the other available GPUs just have a bit of memory taken onto, but nothing really happens there) isn't used at full capacity.  I see mostly 50% usage.  I suspect that it is because of the way the data is loaded.  We're constantly waiting for the data to be loaded on the GPU.

Is is possible to optimize that part?

**Comment by Sawyerb** [comment]
That's normal. The code isn't optimized, and unfortunately, I don't have the bandwidth to optimize it (at least for a few months). If you're interested in speeding it up, I'd recommend checking out the tf.data API.
