### ISSUE TITLE
pool_size and strides question

### ISSUE THREAD

**Issue by pangr** [kuleshov/audio-super-res#36]
When I use the parameter pool_size=8 strides=8 to train the model, the following error will be reported
<img width="1435" alt="图片" src="https://user-images.githubusercontent.com/5838111/115196171-3419d400-a122-11eb-827b-a8b1f3d9c881.png">

**Comment by Sawyerb** [comment]
Thanks for flagging this. I'll make some changes to support pool_size=8 and strides=8. For now, try setting both to 2.

**Comment by Sawyerb** [comment]
It's going to be a while utill I have time to update the code to support a larger pool_size and stride. Again, I recommend setting both to 2.
