### ISSUE TITLE
Colab?

### ISSUE THREAD

**Issue by robbsaber** [kuleshov/audio-super-res#39]
Will this work with colab? Has anyone made a notebook?

**Comment by Sawyerb** [comment]
Yes, (at least I think so). For the project, I ran experiments in a JuyperLab notebook.

**Comment by robbsaber** [comment]
> Yes, (at least I think so). For the project, I ran experiments in a JuyperLab notebook.

Are you able to share it?

**Comment by Sawyerb** [comment]
Unfortunately not. This was years ago, and since I graduated, I no longer have access to my documents on Stanford's servers
