### ISSUE TITLE
Code parameters not matching with paper

### ISSUE THREAD

**Issue by achalshah20** [kuleshov/audio-super-res#4]
Hi Kuleshov,

I was trying to reproduce the results from the paper. But there are few parameters like filter size and number of filters not there in paper so I am using parameters from your code.

There are few things not matching up with the paper:
1. Audio length: 6000 in paper but 8192 in code
2. Filter sizes and strides

Can I reproduce the same results or better results from the paper using the same code?

**Comment by kuleshov** [comment]
I suggest that you use the parameters in the code.
