### ISSUE TITLE
 Memory is not enough

### ISSUE THREAD

**Issue by litong123** [kuleshov/audio-super-res#41]
The memory is not enough when preprocessing the multispeakers dataset and training, and it takes up too much memory. Is there any solution? My computer does not have that much memory.

**Comment by Sawyerb** [comment]
No simple one, unfortunately. I'm certain that the code could be optimized to reduce its memory footprint, but you'd have to dig into it if you want to do so.

**Comment by litong123** [comment]
Can it be improved by simply stream processing the data？Write the h5 file cyclically when preprocessing the dataset, and read the h5 file cyclically when training.

**Comment by litong123** [comment]
What I mean is not that the model occupies too much memory, but that the multispeaker dataset is very large. When preprocessing the dataset, saving the data to the h5 file takes up too much memory. Can it be loaded and saved cyclically? This way it will don't need too much memory.

**Comment by Sawyerb** [comment]
Yes, I think that would work. But again, I don't have the bandwidth to update the code.
