### ISSUE TITLE
SNR decrease for speaker1

### ISSUE THREAD

**Issue by LisaYooD** [kuleshov/audio-super-res#45]
I trained the model for 4kHz to 8kHz, the LSD can be decrease similar with the paper, But the SNR cannot increase, it becomes decrease.
can you give me some suggestions.
python run.py train \
  --train ../data/vctk/speaker1/vctk-speaker1-train.2.16000.8192.4096.h5 \
  --val ../data/vctk/speaker1/vctk-speaker1-val.2.16000.8192.4096.h5 \
  --epochs 500\
  --batch-size 64 \
  --lr 3e-4 \
  --logname singlespeaker \
  --model audiounet \
  --r 2 \
  --layers 4 \
  --piano false \
  --pool_size 2 \
  --strides 2 \
  --full false

**Comment by Sawyerb** [comment]
Have you tried training with the audiotfilm model? It's better than the audiounet one. (That said, SNR should increase during training regardless of which model you use.)
