### ISSUE TITLE
OSError: File ./singlespeaker.lr0.000300.1.g4.b16/model.ckpt-209.data-00000-of-00001.meta does not exist.

### ISSUE THREAD

**Issue by gogo9th** [kuleshov/audio-super-res#47]
Hi, 

I followed README.md to create the trained model for a single speaker. The final terminal output of the training was this:

```
/root/audio-super-res/src/models/model.py:65: FutureWarning: Pass n_fft=2048 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  S = librosa.stft(x, 2048)
List of arrays in input file: ['data', 'label']
Shape of X: (3328, 8192, 1)
Shape of Y: (3328, 8192, 1)
List of arrays in input file: ['data', 'label']
Shape of X: (384, 8192, 1)
Shape of Y: (384, 8192, 1)
audiotfilm
building model...
D-Block:  (None, None, 128)
D-Block:  (None, None, 256)
D-Block:  (None, None, 512)
D-Block:  (None, None, 512)
U-Block:  (None, None, 1024)
U-Block:  (None, None, 1024)
U-Block:  (None, None, 512)
U-Block:  (None, None, 256)
creating train_op with params: {'alg': 'adam', 'lr': 0.0003, 'b1': 0.9, 'b2': 0.999, 'batch_size': 16, 'layers': 4}
Parameters: 68221186
Epoch 1 of 2 took 5730.696s (208 minibatches)
  training l2_loss/segsnr/LSD:      0.007389 15.040772   4.680083
  validation l2_loss/segsnr/LSD:    0.006574 16.088799   4.565674
Epoch 2 of 2 took 12187.555s (208 minibatches)
  training l2_loss/segsnr/LSD:      0.007181 15.214238   4.497891
  validation l2_loss/segsnr/LSD:    0.006336 16.305356   4.398260
```

[These are the trained result files](https://attach.mail.daum.net/bigfile/v1/urls/d/EVSRsEUkiQo3YcQYbU_30iTg1xs/C4j9WBApmPK2V_hZVT74zw). 

Then, I ran the following command to test the trained model:

`$ python3 run.py eval --logname ./singlespeaker.lr0.000300.1.g4.b16/model.ckpt-209.data-00000-of-00001 --out-label singlespeaker-out --wav-file-list ../data/vctk/speaker1/speaker1-val-files.txt --r 4 --pool_size 2 --strides 2 --model audiotfilm`

Then, I get [this error](https://attach.mail.daum.net/bigfile/v1/urls/d/AhECxZ6tgfyLZOzLzVPwwzAWPaQ/C4j9WBApmPJVu8xcr7kfIQ):

`OSError: File ./singlespeaker.lr0.000300.1.g4.b16/model.ckpt-209.data-00000-of-00001.meta does not exist.`

I tried to forcibly change the filename `model.ckpt-209.meta` to `model.ckpt-209.data-00000-of-00001.meta`. Then I get this [error1](https://attach.mail.daum.net/bigfile/v1/urls/d/TXTVdDb2c-yDltqMVUYTaqu8oFM/C4j9WBApmPLm7fmveZi1lQ) and [error2](https://attach.mail.daum.net/bigfile/v1/urls/d/j5mrj8VitB7BW9Y2RTGU-5kVkMk/C4j9WBApmPIKAM_7RKdn8A):

`tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./singlespeaker.lr0.000300.1.g4.b16/model.ckpt-209.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?`

I wonder what could be the reason for this bug. Thanks.

**Comment by Sawyerb** [comment]
Try reverting the filename to what it was originally and running 
` python3 run.py eval --logname ./singlespeaker.lr0.000300.1.g4.b16/model.ckpt-209 --out-label singlespeaker-out --wav-file-list ../data/vctk/speaker1/speaker1-val-files.txt --r 4 --pool_size 2 --strides 2 --model audiotfilm`
