### ISSUE TITLE
makefile error 

### ISSUE THREAD

**Issue by WeeFc** [kuleshov/audio-super-res#48]
when i run 
PATH\audio-super-res-master\data\vctk> make;
make VCTK-Corpus
make[1]: Entering directory 'PATH/audio-super-res-master/data/vctk'
wget http://www.udialogue.org/download/VCTK-Corpus.tar.gz
process_begin: CreateProcess(NULL, wget http://www.udialogue.org/download/VCTK-Corpus.tar.gz, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [Makefile:13: VCTK-Corpus.tar.gz] Error 2
make[1]: Leaving directory 'PATH/audio-super-res-master/data/vctk'
make: *** [Makefile:7: all] Error 2

is this a problem from my side? idk but I think it is from the dataset

**Comment by WMRamadan** [comment]
@WeeFc Reference the answer here https://github.com/kuleshov/audio-super-res/issues/49
