### ISSUE TITLE
where to download the pretrained model?

### ISSUE THREAD

**Issue by xhsoldier** [kuleshov/audio-super-res#5]
I would like to test the model before train it.
Would you provided the pretrained model?
thanks.

**Comment by Frondewu** [comment]
Hi, I wish to test the model too, Could you provide the pretrained model?
thanks in advance!

**Comment by thak123** [comment]
Hi even I want to play with pretrained model. Please release it fast

**Comment by kinnun** [comment]
I wonder if this project has been abandoned? It looks like the training data is no longer online either.

**Comment by Sawyerb** [comment]
Unfortunately, we don't have a pre-trained model to share. If you're interested in testing the model, I would recommend training a singlespeaker model by following the process described in the README. Depending on how many epochs you train for and your hardware, model training should only take a few hours.
