### ISSUE TITLE
Why x_sp will be cut some data in predict?

### ISSUE THREAD

**Issue by whutjolin** [kuleshov/audio-super-res#6]
In `audiounet.py`
```python
def predict(self, X):
    assert len(X) == 1
    x_sp = spline_up(X, self.r) 
    x_sp = x_sp[:len(x_sp) - (len(x_sp) % (2**(self.layers+1)))] # what does these code meaning?
    X = x_sp.reshape((1,len(x_sp),1))
    feed_dict = self.load_batch((X,X), train=False)
    return self.sess.run(self.predictions, feed_dict=feed_dict)
```
Cuold you please tell me why x_sp will be cut like this?
Does it mean the length of X will be changed by through  the whole nereus network?

**Comment by kuleshov** [comment]
Because I'm downsampling the input 2x L times, and for simplicity I assume
that it's divisible by a sufficiently large power of two.
