### ISSUE TITLE
A bug in original paper ?

### ISSUE THREAD

**Issue by kenmaz** [kuleshov/audio-super-res#7]
[Original paper](https://arxiv.org/abs/1708.00853) include incorrect statement at Architectural analysis section.

incorrect (original):
```
the green-ish line display ...
the yellow curve ....
the green curve ....
```

correct:
```
the red line display ...
the green curve ....
the blue curve ....
```

**Comment by Sawyerb** [comment]
You're right. Thanks for flagging this.
