### ISSUE TITLE
OOM when trained on GeForce GTX 1080 

### ISSUE THREAD

**Issue by emmacirl** [kuleshov/audio-super-res#8]
@kuleshov Thanks for your share! When I try to train model with VCTK corpus (1 speaker), I met the OOM problem as below:

 `2018-05-29 06:19:04.735604: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 11 Chunks of size 134217728 totalling 1.38GiB
2018-05-29 06:19:04.735621: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 21 Chunks of size 268435456 totalling 5.25GiB
2018-05-29 06:19:04.735642: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 391118848 totalling 373.00MiB
2018-05-29 06:19:04.735659: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 469762048 totalling 448.00MiB
2018-05-29 06:19:04.735677: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 536870912 totalling 512.00MiB
2018-05-29 06:19:04.735693: I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 9.63GiB
2018-05-29 06:19:04.735715: I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats:
Limit:                 10968950375
InUse:                 10343534592
MaxInUse:              10766956032
NumAllocs:                     267
MaxAllocSize:           4026531840

2018-05-29 06:19:04.735786: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ******************************************************_***********************x******************___
2018-05-29 06:19:04.735827: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[128,2048,512]
Traceback (most recent call last):
  File "run.py", line 111, in <module>
    main()
  File "run.py", line 108, in main
    args.func(args)
  File "run.py", line 76, in train
    model.fit(X_train, Y_train, X_val, Y_val, n_epoch=args.epochs)
  File "audio-super-res/src/models/model.py", line 217, in fit
    tr_objective = self.train(feed_dict)
  File "audio-super-res/src/models/model.py", line 257, in train
    _, loss = self.sess.run([self.train_op, self.loss], feed_dict=feed_dict)
  File "anaconda3/envs/audio-super-res/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "anaconda3/envs/audio-super-res/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "anaconda3/envs/audio-super-res/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "anaconda3/envs/audio-super-res/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[128,2048,512]
         [[Node: generator/upsc_conv1/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](generator/upsc_conv1/subpixel/transpose_1, generator/downsc_conv1/sub, g
enerator/upsc_conv1/concat/axis)]]`

Train command is:
python -u run.py train --train ../data/vctk/speaker1/vctk-speaker1-train.4.16000.8192.4096.h5 --val ../data/vctk/speaker1/vctk-speaker1-val.4.16000.8192.4096.h5  -e 120 --batch-size 128 --lr 3e-4 --logname singlespeaker

And the dimention of train and test data is:
List of arrays in input file: [u'data', u'label']
Shape of X: (3328, 8192, 1)
Shape of Y: (3328, 8192, 1)
List of arrays in input file: [u'data', u'label']
Shape of X: (384, 8192, 1)
Shape of Y: (384, 8192, 1)

The environment configuration is:
tensorflow-gpu==0.12.1
keras==1.2.1
numpy==1.12.0
scipy==0.18.1
librosa==0.4.3
h5py==2.6.0

The data is not very huge, why occur OOM problem? I don't understand. Do you know ?

**Comment by kuleshov** [comment]
Hi and sorry for the late response. It seems to me like your batch size is
too large right now, try 64 or 32.

**Comment by LavenderMP** [comment]
> @kuleshov Thanks for your share! When I try to train model with VCTK corpus (1 speaker), I met the OOM problem as below:
> 
> `2018-05-29 06:19:04.735604: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 11 Chunks of size 134217728 totalling 1.38GiB
> 2018-05-29 06:19:04.735621: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 21 Chunks of size 268435456 totalling 5.25GiB
> 2018-05-29 06:19:04.735642: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 391118848 totalling 373.00MiB
> 2018-05-29 06:19:04.735659: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 469762048 totalling 448.00MiB
> 2018-05-29 06:19:04.735677: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 536870912 totalling 512.00MiB
> 2018-05-29 06:19:04.735693: I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 9.63GiB
> 2018-05-29 06:19:04.735715: I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats:
> Limit: 10968950375
> InUse: 10343534592
> MaxInUse: 10766956032
> NumAllocs: 267
> MaxAllocSize: 4026531840
> 
> 2018-05-29 06:19:04.735786: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ******************************************************_***********************x******************___
> 2018-05-29 06:19:04.735827: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[128,2048,512]
> Traceback (most recent call last):
> File "run.py", line 111, in 
> main()
> File "run.py", line 108, in main
> args.func(args)
> File "run.py", line 76, in train
> model.fit(X_train, Y_train, X_val, Y_val, n_epoch=args.epochs)
> File "audio-super-res/src/models/model.py", line 217, in fit
> tr_objective = self.train(feed_dict)
> File "audio-super-res/src/models/model.py", line 257, in train
> _, loss = self.sess.run([self.train_op, self.loss], feed_dict=feed_dict)
> File "anaconda3/envs/audio-super-res/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
> run_metadata_ptr)
> File "anaconda3/envs/audio-super-res/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
> feed_dict_string, options, run_metadata)
> File "anaconda3/envs/audio-super-res/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
> target_list, options, run_metadata)
> File "anaconda3/envs/audio-super-res/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[128,2048,512]
> [[Node: generator/upsc_conv1/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](generator/upsc_conv1/subpixel/transpose_1, generator/downsc_conv1/sub, g
> enerator/upsc_conv1/concat/axis)]]`
> 
> Train command is:
> python -u run.py train --train ../data/vctk/speaker1/vctk-speaker1-train.4.16000.8192.4096.h5 --val ../data/vctk/speaker1/vctk-speaker1-val.4.16000.8192.4096.h5 -e 120 --batch-size 128 --lr 3e-4 --logname singlespeaker
> 
> And the dimention of train and test data is:
> List of arrays in input file: [u'data', u'label']
> Shape of X: (3328, 8192, 1)
> Shape of Y: (3328, 8192, 1)
> List of arrays in input file: [u'data', u'label']
> Shape of X: (384, 8192, 1)
> Shape of Y: (384, 8192, 1)
> 
> The environment configuration is:
> tensorflow-gpu==0.12.1
> keras==1.2.1
> numpy==1.12.0
> scipy==0.18.1
> librosa==0.4.3
> h5py==2.6.0
> 
> The data is not very huge, why occur OOM problem? I don't understand. Do you know ?

what cuda version did you use back then?

**Comment by LavenderMP** [comment]
> Hi and sorry for the late response. It seems to me like your batch size is too large right now, try 64 or 32.
> […](#)

did you use tensorflow-gpu for training?

**Comment by Sawyerb** [comment]
Yes, we did.
