### ISSUE TITLE
Resize-convolution instead of subpixel convolution 

### ISSUE THREAD

**Issue by ahmed-fau** [kuleshov/audio-super-res#9]
Hi,

Thanks for this implementation. 

Regarding the sub-pixel convolution approach for up-sampling the signal .. do you think that this was better than nearest-neighbor resize followed by convolution as argued by Odena [here](https://distill.pub/2016/deconv-checkerboard/) ? Because he says that the latter is better.

Thanks in advance

**Comment by kuleshov** [comment]
I'm not sure, I don't think I tried all the methods proposed by Odena. I
think one of the arguments there is that the difference between the
upscaling methods is less important if the upscaling ratio divides the
dimensions of the input, but it may still be useful to do it.

There are definitely artifacts that are introduced from the upscaling
method. I would be really curious to know how different methods affect the
artifacts. So if you want to try that, it would be definitely really cool.

One reference worth looking at is the WaveGAN paper, they discuss this
issue in some detail.
